### DISCUSSION TITLE
Source not found: File outside of allowed directories.solidity(6275)

### DISCUSSION THREAD

**Discussion by BikalpaRegmi** [Cyfrin/security-and-auditing-full-course-s23#322] [Q&A] [answered]
Why do i keep getting this warning or error even  if i have allowed them in my foundry.toml

**These are my import in (PuppyRaffle.sol) -:**
```solidity
import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Address} from "@openzeppelin/contracts/utils/Address.sol";
import {Base64} from "lib/base64/base64.sol";
```

**Also in my Test File (PuppyRaffleTest.t) -:**
```solidity
import {Test, console} from "forge-std/Test.sol";
import {PuppyRaffle} from "../src/PuppyRaffle.sol";
```

**My Toml File -:**
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["src", "lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
```

**The Error Like this in all of my imports.-:**
`Source "lib/openzeppelin-contracts/contracts/token/ERC721/ERC721.sol" not found: File outside of allowed directories.`

_May be this is an silly issue because I came from hardhat background.  I'll be glad if someone helped me._
